### ISSUE TITLE
Media player

### ISSUE THREAD

**Issue by nyouness** [prayag17/JellyPlayer#203]
Hii , ty a loot for your great work i really like it and my only request is a way to use MPV because i have portable config with scripts and shaders for anime and live action. OR add option to make external player as default

**Comment by prayag17** [comment]
There is no active mpv binding for rust and no way to native canvas like opengl ctx for mpv to paint video frames on or even a good mov ipc wrapper so that it can open an external mpv video. 

But maybe in the future when tauri's egui project that is stable I might **think** to use something like gstreamer which has an excellent rust library for their player.
