### ISSUE TITLE
frequent errors when opening items `undefined is not an object (evaluating 'r.data.ParentLogoItemId.length')`

### ISSUE THREAD

**Issue by foss-** [prayag17/JellyPlayer#259]
**Describe the bug**
When clicking item on home view,  instead of opening item details, an error is shown.

**To Reproduce**
1. Click on album cover on home screen
2. see error: Something went wrong: undefined is not an object (evaluating 'r.data.ParentBackdropImageTags[0]')
Also happens for photos or movies or TV shows.

**Expected behavior**
Show item details

**Screenshots**
![1](https://github.com/prayag17/JellyPlayer/assets/5708172/dae33b7e-04c1-4875-865d-9e7e38f6be87)

**Desktop (please complete the following information):**
 - OS: macOS 13.6.4
 - Version 0.0.4-dev

**Comment by prayag17** [comment]
Is this still an issue with [latest builds](https://github.com/prayag17/JellyPlayer/actions/runs/8029617464)?

**Comment by foss-** [comment]
Should this be closed?

In 0.0.5-dev (20240317.114520) just tried to load an album view which loaded a blank page and no way to return to a functional view.

Other albums are not loading but error message has changed:

`Something went wrong: undefined is not an object (evaluating 'r.data.ParentBackdropImageTags[0]')`

**Comment by wolflord212312** [comment]
On windows i have encountered something like this on the latest And its odd as only happens when i click on a 

When Clicking on a EP to view info on the EP itself rather then a series i get some form of these errors

![image](https://github.com/prayag17/JellyPlayer/assets/47831173/2ae7e795-f3c1-484a-9775-2b85d7083ac9)
![image](https://github.com/prayag17/JellyPlayer/assets/47831173/c263e8d8-fab7-4ea2-889d-eeb834118762)

one reads 0 as im assuming it does not like that the EP has no description who knows 

But the first one is undefined length

**Comment by prayag17** [comment]
Closing this in favor of #338

**Comment by foss-** [comment]
Doesn't this make it harder to keep track of the individual issues, their state and discussing one issue at a time?

**Comment by prayag17** [comment]
This issue is related to multiple components and routes and is not really a page specific issue
